import Dashboard from "@/components/Dashboard";
import WaterAnalyticsDashboard from "@/components/WaterAnanlyticDashboard";
import React from "react";
import FitnessAdvisor from "../pf/page";
import Calendar from "@/components/Calander";
import PowerBIEmbedReport from "@/components/PowerBIEmbedReport";
// import PowerBIReport from "@/components/PowerBIEmbed";

export default function page() {
  return (
    <div
      style={{
        marginTop: "-20px",
        background:
          "linear-gradient(to bottom right, rgba(113, 0, 135, 0.7) 0%, rgba(70, 0, 70, 0.6) 15%, rgb(15, 15, 15) 35%, rgb(15, 15, 15) 65%, rgba(80, 50, 0, 0.5) 85%, rgba(121, 76, 0, 0.7) 100%)",
      }}
    >
      {/* <PowerBIEmbedReport></PowerBIEmbedReport> */}
      {/* <WaterAnalyticsDashboard></WaterAnalyticsDashboard> */}
      {/* <PowerBIReport></PowerBIReport> */}
      {/* <PowerBIEmbedReport></PowerBIEmbedReport> */}

      <Dashboard></Dashboard>
      <FitnessAdvisor></FitnessAdvisor>
      <Calendar></Calendar>
    </div>
  );
}
// "use client";
// import { useEffect, useState } from "react";
// import { PowerBIEmbed } from "powerbi-client-react";

// const PowerBIEmbedReport = () => {
//   const [embedConfig, setEmbedConfig] = useState(null);

//   useEffect(() => {
//     // Sample API call to get the Embed Token (You will have to implement the API call)
//     // This should be done via a backend to keep your token safe
//     fetch("/api/getPowerBIEmbedConfig")
//       .then((response) => response.json())
//       .then((data) => {
//         const config = {
//           type: "report",
//           tokenType: "Embed",
//           accessToken: data.embedToken, // Use the embed token returned from the backend API
//           embedUrl: data.embedUrl, // Embed URL generated by Power BI API
//           id: data.reportId, // Report ID (already available from your API response)
//           permissions: 1, // Read permission
//           settings: {
//             filterPaneEnabled: true,
//             navContentPaneEnabled: true,
//           },
//         };
//         setEmbedConfig(config);
//       })
//       .catch((error) => {
//         console.error("Error fetching embed config: ", error);
//       });
//   }, []);

//   return (
//     <div>
//       <h2>Weight Change over a Month</h2>
//       {embedConfig ? (
//         <PowerBIEmbed embedConfig={embedConfig} />
//       ) : (
//         <p>Loading the report...</p>
//       )}
//     </div>
//   );
// };

// export default PowerBIEmbedComponent;
